# Generated by Django 4.2.13 on 2024-09-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('USA', 'Estados Unidos'), ('Brazil', 'Brasil'), ('France', 'França'), ('Germany', 'Alemanha'), ('Argentina', 'Argentina')], max_length=100)),
            ],
        ),
    ]
